#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
ALEMBIC_CONFIG="$BACKEND_ROOT/alembic.ini"
LOG_FILE="${MIGRATION_LOG:-$SCRIPT_DIR/migration.log}"

usage() {
    cat <<EOF
Usage: $(basename "$0") {status|upgrade [target]|downgrade [target]|revision [message]|history}

Commands:
  status              Show current migration and available heads
  upgrade [target]    Upgrade database to target revision (default: head)
  downgrade [target]  Downgrade database to target revision (default: -1)
  revision [message]  Create an autogenerated migration
  history             Show migration history
EOF
}

log_with_header() {
    printf '\n[%s] --- %s ---\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$1" >> "$LOG_FILE"
}

run_alembic() {
    if command -v alembic >/dev/null 2>&1; then
        alembic -c "$ALEMBIC_CONFIG" "$@"
    else
        python -m alembic -c "$ALEMBIC_CONFIG" "$@"
    fi
}

activate_venv_if_present() {
    if [ -f "$BACKEND_ROOT/venv/Scripts/activate" ]; then
        # shellcheck disable=SC1091
        source "$BACKEND_ROOT/venv/Scripts/activate"
    elif [ -f "$BACKEND_ROOT/venv/bin/activate" ]; then
        # shellcheck disable=SC1091
        source "$BACKEND_ROOT/venv/bin/activate"
    fi
}

if [ ! -f "$ALEMBIC_CONFIG" ]; then
    echo "Error: alembic.ini not found at $ALEMBIC_CONFIG" >&2
    exit 1
fi

activate_venv_if_present
export PYTHONPATH="$BACKEND_ROOT${PYTHONPATH:+:$PYTHONPATH}"
cd "$BACKEND_ROOT"

command="${1:-}"
if [ -z "$command" ]; then
    usage
    exit 1
fi
shift || true

echo "Backend root: $BACKEND_ROOT"
echo "Alembic config: $ALEMBIC_CONFIG"
echo "Log file: $LOG_FILE"

case "$command" in
    status)
        echo "Checking migration status ..."
        run_alembic current
        run_alembic heads
        ;;
    upgrade)
        target="${1:-head}"
        log_with_header "Upgrade to $target"
        echo "Upgrading database to $target ..."
        if run_alembic upgrade "$target" >> "$LOG_FILE" 2>&1; then
            echo "Migration successful."
        else
            echo "Migration failed. Check $LOG_FILE."
            exit 1
        fi
        ;;
    downgrade)
        target="${1:--1}"
        log_with_header "Downgrade to $target"
        echo "Downgrading database to $target ..."
        if run_alembic downgrade "$target" >> "$LOG_FILE" 2>&1; then
            echo "Downgrade successful."
        else
            echo "Downgrade failed. Check $LOG_FILE."
            exit 1
        fi
        ;;
    revision)
        message="${*:-auto-migration}"
        log_with_header "Revision: $message"
        echo "Creating new revision: $message"
        if run_alembic revision --autogenerate -m "$message" >> "$LOG_FILE" 2>&1; then
            echo "Revision created."
        else
            echo "Revision failed. Check $LOG_FILE."
            exit 1
        fi
        ;;
    history)
        run_alembic history
        ;;
    *)
        usage
        exit 1
        ;;
esac
