"""Added c_at, u_at, & d_at columns on categories schema.

Revision ID: 550233925a2d
Revises: c27694a858d2
Create Date: 2026-07-19 15:14:45.364671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550233925a2d'
down_revision: Union[str, Sequence[str], None] = 'c27694a858d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_unique_constraint('uq_categories_name', 'categories', ['name'])
    op.create_index('ix_sms_payments_provider_reference', 'sms_payments', ['provider_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sms_payments_provider_reference', table_name='sms_payments')
    op.drop_constraint('uq_categories_name', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('categories', 'deleted_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
