"""Removed billing and projects.

Revision ID: 8dea867ad60e
Revises: 9e42755810da
Create Date: 2026-08-09 18:00:26.082185

"""
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dea867ad60e'
down_revision: Union[str, Sequence[str], None] = '9e42755810da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Set this environment variable to acknowledge that the drops below are
#: permanent. It is deliberately required, because this revision runs as part
#: of ``alembic upgrade head``, which docker-entrypoint.sh runs on every
#: container start: without a gate, standing up the service against a database
#: that predates this revision silently destroyed three tables' contents.
#: downgrade() recreates the schema but not the rows.
DESTRUCTIVE_ACK_ENV_VAR = 'TECHPULSE_ALLOW_DESTRUCTIVE_MIGRATIONS'

_DROPPED_TABLES = ('projects', 'sms_purchases', 'sms_payments')


def _destructive_ops_acknowledged() -> bool:
    return (os.environ.get(DESTRUCTIVE_ACK_ENV_VAR) or '').strip().lower() in {
        '1', 'true', 'yes', 'on',
    }


def upgrade() -> None:
    """Upgrade schema."""
    if not _destructive_ops_acknowledged():
        tables = ', '.join(_DROPPED_TABLES)
        raise RuntimeError(
            f"Revision {revision} permanently drops the tables {tables} and "
            f"their contents. It cannot be undone by downgrade(), which only "
            f"recreates the empty schema. Take a backup, then re-run with "
            f"{DESTRUCTIVE_ACK_ENV_VAR}=1 to confirm you accept the loss. "
            f"To leave the legacy tables in place instead, mark this revision "
            f"as applied without running it: "
            f"alembic stamp {revision}"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_public_id_desc'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_user_id_id_desc'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_sms_purchases_buyer_id'), table_name='sms_purchases')
    op.drop_index(op.f('ix_sms_purchases_software_id'), table_name='sms_purchases')
    op.drop_table('sms_purchases')
    op.drop_index(op.f('ix_sms_payments_buyer_id'), table_name='sms_payments')
    op.drop_index(op.f('ix_sms_payments_provider_reference'), table_name='sms_payments')
    op.drop_index(op.f('ix_sms_payments_software_id'), table_name='sms_payments')
    op.drop_index(op.f('ix_sms_payments_status'), table_name='sms_payments')
    op.drop_table('sms_payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_payments',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('software_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('amount_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('provider_reference', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['sms_softwares.id'], name=op.f('sms_payments_software_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sms_payments_pkey'))
    )
    op.create_index(op.f('ix_sms_payments_status'), 'sms_payments', ['status'], unique=False)
    op.create_index(op.f('ix_sms_payments_software_id'), 'sms_payments', ['software_id'], unique=False)
    op.create_index(op.f('ix_sms_payments_provider_reference'), 'sms_payments', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_sms_payments_buyer_id'), 'sms_payments', ['buyer_id'], unique=False)
    op.create_table('sms_purchases',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('software_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('amount_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('purchased_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('refunded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('lock_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['sms_payments.id'], name=op.f('sms_purchases_payment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['software_id'], ['sms_softwares.id'], name=op.f('sms_purchases_software_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sms_purchases_pkey')),
    sa.UniqueConstraint('software_id', 'buyer_id', name=op.f('uq_sms_purchases_software_buyer'))
    )
    op.create_index(op.f('ix_sms_purchases_software_id'), 'sms_purchases', ['software_id'], unique=False)
    op.create_index(op.f('ix_sms_purchases_buyer_id'), 'sms_purchases', ['buyer_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('download_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('projects_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index(op.f('ix_projects_user_id_id_desc'), 'projects', ['user_id', 'id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_is_public_id_desc'), 'projects', ['is_public', 'id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    # ### end Alembic commands ###
