"""Added deletion tracking in sftw table

Revision ID: 952359f24a21
Revises: 20260422_0009
Create Date: 2026-06-22 11:15:57.309820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '952359f24a21'
down_revision: Union[str, Sequence[str], None] = '20260422_0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_softwares_created_at'), table_name='sms_softwares')
    op.drop_index(op.f('ix_sms_softwares_current_version_id'), table_name='sms_softwares')
    op.drop_index(op.f('ix_sms_softwares_owner_id'), table_name='sms_softwares')
    op.drop_table('sms_softwares')
    op.drop_index(op.f('ix_transcriptions_id'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_user_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_sms_artifacts_created_at'), table_name='sms_artifacts')
    op.drop_index(op.f('ix_sms_artifacts_file_hash'), table_name='sms_artifacts')
    op.drop_table('sms_artifacts')
    op.drop_index(op.f('ix_audit_events_actor_occurred'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_ip_occurred'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_type_occurred'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_security_alerts_ack_created'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_created_at'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_rule_created'), table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index(op.f('ix_sms_idempotency_created_at'), table_name='sms_idempotency_keys')
    op.drop_index(op.f('ix_sms_idempotency_scope_actor'), table_name='sms_idempotency_keys')
    op.drop_table('sms_idempotency_keys')
    op.drop_index(op.f('ix_sms_versions_created_at'), table_name='sms_versions')
    op.drop_index(op.f('ix_sms_versions_software_id'), table_name='sms_versions')
    op.drop_index(op.f('ix_sms_versions_software_id_version'), table_name='sms_versions')
    op.drop_index(op.f('ix_sms_versions_status'), table_name='sms_versions')
    op.drop_table('sms_versions')
    op.create_index('ix_projects_is_public_id_desc', 'projects', ['is_public', 'id'], unique=False)
    op.create_index('ix_projects_user_id_id_desc', 'projects', ['user_id', 'id'], unique=False)
    op.drop_constraint(op.f('resources_slug_key'), 'resources', type_='unique')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True)
    op.drop_index(op.f('ix_users_verification_email_next_retry_at'), table_name='users')
    op.create_index('ix_users_verification_retry_lookup', 'users', ['status', 'created_at', 'verification_email_next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_verification_retry_lookup', table_name='users')
    op.create_index(op.f('ix_users_verification_email_next_retry_at'), 'users', ['verification_email_next_retry_at'], unique=False)
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_unique_constraint(op.f('resources_slug_key'), 'resources', ['slug'])
    op.drop_index('ix_projects_user_id_id_desc', table_name='projects')
    op.drop_index('ix_projects_is_public_id_desc', table_name='projects')
    op.create_table('sms_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('software_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('artifact_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('download_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=False),
    sa.Column('deprecated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'DEPRECATED'::character varying, 'REVOKED'::character varying]::text[])", name=op.f('ck_sms_versions_status')),
    sa.ForeignKeyConstraint(['artifact_id'], ['sms_artifacts.id'], name=op.f('sms_versions_artifact_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['software_id'], ['sms_softwares.id'], name=op.f('sms_versions_software_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sms_versions_pkey')),
    sa.UniqueConstraint('artifact_id', name=op.f('sms_versions_artifact_id_key')),
    sa.UniqueConstraint('software_id', 'version', name=op.f('uq_sms_versions_software_version'))
    )
    op.create_index(op.f('ix_sms_versions_status'), 'sms_versions', ['status'], unique=False)
    op.create_index(op.f('ix_sms_versions_software_id_version'), 'sms_versions', ['software_id', 'version'], unique=False)
    op.create_index(op.f('ix_sms_versions_software_id'), 'sms_versions', ['software_id'], unique=False)
    op.create_index(op.f('ix_sms_versions_created_at'), 'sms_versions', ['created_at'], unique=False)
    op.create_table('sms_idempotency_keys',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('request_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('response_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sms_idempotency_keys_pkey')),
    sa.UniqueConstraint('scope', 'actor_id', 'key', name=op.f('uq_sms_idempotency_scope_actor_key'))
    )
    op.create_index(op.f('ix_sms_idempotency_scope_actor'), 'sms_idempotency_keys', ['scope', 'actor_id'], unique=False)
    op.create_index(op.f('ix_sms_idempotency_created_at'), 'sms_idempotency_keys', ['created_at'], unique=False)
    op.create_table('security_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_code', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('actor_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('audit_event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acknowledged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('acknowledged_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['audit_event_id'], ['audit_events.id'], name=op.f('security_alerts_audit_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('security_alerts_pkey'))
    )
    op.create_index(op.f('ix_security_alerts_rule_created'), 'security_alerts', ['rule_code', 'created_at'], unique=False)
    op.create_index(op.f('ix_security_alerts_created_at'), 'security_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_alerts_ack_created'), 'security_alerts', ['acknowledged', 'created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('actor_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_events_pkey'))
    )
    op.create_index(op.f('ix_audit_events_type_occurred'), 'audit_events', ['event_type', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_ip_occurred'), 'audit_events', ['ip_address', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_occurred'), 'audit_events', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_table('sms_artifacts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sms_artifacts_pkey')),
    sa.UniqueConstraint('storage_key', name=op.f('sms_artifacts_storage_key_key'))
    )
    op.create_index(op.f('ix_sms_artifacts_file_hash'), 'sms_artifacts', ['file_hash'], unique=False)
    op.create_index(op.f('ix_sms_artifacts_created_at'), 'sms_artifacts', ['created_at'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('audio_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('transcript_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('transcriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transcriptions_pkey'))
    )
    op.create_index(op.f('ix_transcriptions_user_id'), 'transcriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_transcriptions_id'), 'transcriptions', ['id'], unique=False)
    op.create_table('sms_softwares',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('row_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('current_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_version_id'], ['sms_versions.id'], name=op.f('fk_sms_softwares_current_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('sms_softwares_pkey')),
    sa.UniqueConstraint('owner_id', 'name', name=op.f('uq_sms_software_owner_name'))
    )
    op.create_index(op.f('ix_sms_softwares_owner_id'), 'sms_softwares', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sms_softwares_current_version_id'), 'sms_softwares', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_sms_softwares_created_at'), 'sms_softwares', ['created_at'], unique=False)
    # ### end Alembic commands ###
