"""Added a download_count row

Revision ID: 9e42755810da
Revises: 550233925a2d
Create Date: 2026-07-23 14:26:58.974989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e42755810da'
down_revision: Union[str, Sequence[str], None] = '550233925a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_softwares', sa.Column('download_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_softwares', 'download_count')
    # ### end Alembic commands ###
