---
references:
  - "Folder: /techpulse_backend/app/modules/billing"
generationTime: 2026-07-08T12:14:40.864Z
---
architecture-beta
    group api(cloud)[API Layer]
    group database(cloud)[Data Layer]

    service webapp(server)[Web App] in api
    service registry(server)[Payment Gateway Registry] in api
    service auth(server)[Auth Service] in api
    service db(database)[Database] in database

    webapp:R --> L:registry
    webapp:R --> L:auth
    webapp:B --> T:db